# Generated by Django 5.2.7 on 2026-01-17 22:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornalero',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'unique_together': {('fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornalero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='base.jornalero')),
                ('periodos', models.ManyToManyField(blank=True, related_name='calendarios', to='base.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('plazas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('euros_hora', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(9)])),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='base.periodo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='base.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('interesado', models.CharField(choices=[('jornalero', 'Jornalero'), ('propietario', 'Propietario')], max_length=11)),
                ('jornalero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='base.jornalero')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='base.oferta')),
            ],
            options={
                'unique_together': {('jornalero', 'oferta')},
            },
        ),
    ]
